# Generated by Django 5.1.2 on 2024-10-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lw_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lw',
            name='age',
        ),
        migrations.RemoveField(
            model_name='lw',
            name='country',
        ),
        migrations.RemoveField(
            model_name='lw',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='lw',
            name='position',
        ),
        migrations.RemoveField(
            model_name='lw',
            name='reason',
        ),
    ]
