# Generated by Django 5.1.2 on 2025-02-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lw_post', '0003_alter_lw_lastwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='lw',
            name='seed_screen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lw',
            name='seed_x',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
