# Generated by Django 5.1.2 on 2025-06-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lw_post', '0004_lw_seed_screen_lw_seed_x'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
